import { NextResponse } from 'next/server'

/**
 * GET /api/menu/demo
 * Returns a hardcoded demo restaurant menu — no database required.
 * Used for the "View Demo" button on the landing page.
 */
export async function GET() {
  const restaurant = {
    id: 'demo-restaurant-id',
    owner_user_id: 'demo-user-id',
    name_en: 'Spice Garden — Demo',
    name_ar: 'حديقة التوابل',
    name_hi: null,
    slug: 'demo',
    logo_url: null,
    cover_image_url: null,
    cuisine_type: 'Indian',
    whatsapp_number: '+919876543210',
    phone: null,
    address_en: '12, MG Road, Bengaluru',
    address_ar: null,
    address_hi: null,
    area: null,
    google_maps_url: null,
    currency: 'INR',
    gst_percentage: 5,
    gst_type: 'exclusive',
    show_gst: true,
    is_veg_only: false,
    default_language: 'en',
    accept_orders: true,
    operating_hours: null,
    plan: 'paid',
    trial_ends_at: '2099-12-31T00:00:00Z',
    subscription_active: true,
    total_menu_views: 1234,
    total_whatsapp_orders: 567,
    monthly_fee_inr: 299,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }

  const categories = [
    {
      id: 'cat-starters',
      restaurant_id: 'demo-restaurant-id',
      name_en: 'Starters',
      name_ar: 'المقبلات',
      name_hi: null,
      description_en: 'Start your meal right',
      description_ar: null,
      description_hi: null,
      image_url: null,
      sort_order: 1,
      is_active: true,
      available_from: null,
      available_until: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'cat-mains',
      restaurant_id: 'demo-restaurant-id',
      name_en: 'Main Course',
      name_ar: 'الأطباق الرئيسية',
      name_hi: null,
      description_en: 'Hearty mains to fill you up',
      description_ar: null,
      description_hi: null,
      image_url: null,
      sort_order: 2,
      is_active: true,
      available_from: null,
      available_until: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'cat-drinks',
      restaurant_id: 'demo-restaurant-id',
      name_en: 'Drinks',
      name_ar: 'المشروبات',
      name_hi: null,
      description_en: 'Cool off with our refreshing drinks',
      description_ar: null,
      description_hi: null,
      image_url: null,
      sort_order: 3,
      is_active: true,
      available_from: null,
      available_until: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'cat-desserts',
      restaurant_id: 'demo-restaurant-id',
      name_en: 'Desserts',
      name_ar: 'الحلويات',
      name_hi: null,
      description_en: 'Something sweet to finish',
      description_ar: null,
      description_hi: null,
      image_url: null,
      sort_order: 4,
      is_active: true,
      available_from: null,
      available_until: null,
      created_at: new Date().toISOString(),
    },
  ]

  const items = [
    // Starters
    {
      id: 'item-1', restaurant_id: 'demo-restaurant-id', category_id: 'cat-starters',
      name_en: 'Paneer Tikka', name_ar: 'تيكا بانير', name_hi: null,
      description_en: 'Marinated cottage cheese cubes grilled in tandoor with bell peppers and onions.',
      description_ar: 'قطع جبن القريش المتبلة مشوية في التنور مع الفلفل والبصل.',
      description_hi: null,
      price: 249, original_price: 299,
      image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&auto=format&fit=crop',
      is_available: true, is_featured: true, is_spicy: false, is_veg: true, is_jain: false, is_new: false,
      allergens: null, customisation_groups: [], sort_order: 1,
      created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    },
    {
      id: 'item-2', restaurant_id: 'demo-restaurant-id', category_id: 'cat-starters',
      name_en: 'Chicken Seekh Kebab', name_ar: 'كباب الدجاج السيخ', name_hi: null,
      description_en: 'Minced chicken mixed with spices, skewered and cooked in our clay oven.',
      description_ar: null, description_hi: null,
      price: 349, original_price: null,
      image_url: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&auto=format&fit=crop',
      is_available: true, is_featured: false, is_spicy: true, is_veg: false, is_jain: false, is_new: true,
      allergens: null, customisation_groups: [], sort_order: 2,
      created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    },
    {
      id: 'item-3', restaurant_id: 'demo-restaurant-id', category_id: 'cat-starters',
      name_en: 'Veg Spring Rolls', name_ar: 'لفائف الخضار', name_hi: null,
      description_en: 'Crispy golden rolls stuffed with fresh vegetables and glass noodles.',
      description_ar: null, description_hi: null,
      price: 199, original_price: null,
      image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&auto=format&fit=crop',
      is_available: true, is_featured: false, is_spicy: false, is_veg: true, is_jain: false, is_new: false,
      allergens: null, customisation_groups: [], sort_order: 3,
      created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    },
    // Mains
    {
      id: 'item-4', restaurant_id: 'demo-restaurant-id', category_id: 'cat-mains',
      name_en: 'Butter Chicken', name_ar: 'دجاج بالزبدة', name_hi: null,
      description_en: 'Tender chicken in a rich, creamy tomato-based sauce. A classic favourite.',
      description_ar: 'دجاج طري في صلصة طماطم كريمية غنية. من الأطباق الكلاسيكية المفضلة.',
      description_hi: null,
      price: 399, original_price: 449,
      image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400&auto=format&fit=crop',
      is_available: true, is_featured: true, is_spicy: false, is_veg: false, is_jain: false, is_new: false,
      allergens: ['dairy'], customisation_groups: [
        { name: 'Spice Level', options: [
          { label: 'Mild', price_add: 0 },
          { label: 'Medium', price_add: 0 },
          { label: 'Hot', price_add: 0 },
        ], required: true }
      ], sort_order: 1,
      created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    },
    {
      id: 'item-5', restaurant_id: 'demo-restaurant-id', category_id: 'cat-mains',
      name_en: 'Dal Makhani', name_ar: 'دال ماخاني', name_hi: null,
      description_en: 'Slow-cooked black lentils with cream, butter and aromatic spices.',
      description_ar: null, description_hi: null,
      price: 299, original_price: null,
      image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&auto=format&fit=crop',
      is_available: true, is_featured: false, is_spicy: false, is_veg: true, is_jain: false, is_new: false,
      allergens: ['dairy'], customisation_groups: [], sort_order: 2,
      created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    },
    {
      id: 'item-6', restaurant_id: 'demo-restaurant-id', category_id: 'cat-mains',
      name_en: 'Mutton Biryani', name_ar: 'برياني لحم الغنم', name_hi: null,
      description_en: 'Fragrant basmati rice layered with slow-cooked mutton, saffron and fried onions.',
      description_ar: null, description_hi: null,
      price: 549, original_price: null,
      image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&auto=format&fit=crop',
      is_available: true, is_featured: true, is_spicy: true, is_veg: false, is_jain: false, is_new: false,
      allergens: null, customisation_groups: [], sort_order: 3,
      created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    },
    // Drinks
    {
      id: 'item-7', restaurant_id: 'demo-restaurant-id', category_id: 'cat-drinks',
      name_en: 'Mango Lassi', name_ar: 'لاسي المانجو', name_hi: null,
      description_en: 'Chilled yoghurt blended with fresh Alphonso mango pulp and a pinch of cardamom.',
      description_ar: null, description_hi: null,
      price: 149, original_price: null,
      image_url: 'https://images.unsplash.com/photo-1605364081928-dc8c4a1e73d5?w=400&auto=format&fit=crop',
      is_available: true, is_featured: false, is_spicy: false, is_veg: true, is_jain: true, is_new: false,
      allergens: ['dairy'], customisation_groups: [], sort_order: 1,
      created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    },
    {
      id: 'item-8', restaurant_id: 'demo-restaurant-id', category_id: 'cat-drinks',
      name_en: 'Masala Chai', name_ar: 'شاي بالمسالا', name_hi: null,
      description_en: 'Brewed with ginger, cardamom, cinnamon and cloves — the perfect Indian tea.',
      description_ar: null, description_hi: null,
      price: 79, original_price: null,
      image_url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&auto=format&fit=crop',
      is_available: true, is_featured: false, is_spicy: false, is_veg: true, is_jain: true, is_new: false,
      allergens: ['dairy'], customisation_groups: [], sort_order: 2,
      created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    },
    // Desserts
    {
      id: 'item-9', restaurant_id: 'demo-restaurant-id', category_id: 'cat-desserts',
      name_en: 'Gulab Jamun', name_ar: 'جلاب جامون', name_hi: null,
      description_en: 'Soft milk-solid dumplings soaked in rose-flavoured sugar syrup. Served warm.',
      description_ar: null, description_hi: null,
      price: 129, original_price: null,
      image_url: 'https://images.unsplash.com/photo-1666507046536-72f285f3e2c7?w=400&auto=format&fit=crop',
      is_available: true, is_featured: false, is_spicy: false, is_veg: true, is_jain: false, is_new: false,
      allergens: ['dairy', 'gluten'], customisation_groups: [], sort_order: 1,
      created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    },
    {
      id: 'item-10', restaurant_id: 'demo-restaurant-id', category_id: 'cat-desserts',
      name_en: 'Kulfi Falooda', name_ar: 'كولفي فالودة', name_hi: null,
      description_en: 'Traditional Indian ice cream with rose syrup, basil seeds and vermicelli noodles.',
      description_ar: null, description_hi: null,
      price: 179, original_price: null,
      image_url: 'https://images.unsplash.com/photo-1633878648432-af24cc3741e5?w=400&auto=format&fit=crop',
      is_available: true, is_featured: true, is_spicy: false, is_veg: true, is_jain: false, is_new: true,
      allergens: ['dairy'], customisation_groups: [], sort_order: 2,
      created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
    },
  ]

  return NextResponse.json(
    { restaurant, categories, items },
    {
      headers: {
        'Cache-Control': 'public, max-age=60, stale-while-revalidate=120',
      },
    }
  )
}
